[build]
  base    = "/"
  publish = "/public"
  command = "npm run build"

[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[redirects]]
  from    = "/youth2business"
  to      = "/404"
  status  = 301

[[redirects]]
  from    = "/banff"
  to      = "https://karen1337.typeform.com/to/ZMRewG"
  status  = 301
